---
title: "Some Universities Located in Hanoi"
subtitle: "R for Fun"
author: "Nguyen Chi Dung"

output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'), warning = FALSE, message = FALSE)
options(htmltools.dir.version = FALSE)
```

```{r}
# Lấy dữ liệu địa chỉ - tên của các trường ĐH ở HN: 
rm(list = ls())
library(rvest)
library(tidyverse)

my_link <- "https://vi.wikipedia.org/wiki/Danh_s%C3%A1ch_tr%C6%B0%E1%BB%9Dng_%C4%91%E1%BA%A1i_h%E1%BB%8Dc,_h%E1%BB%8Dc_vi%E1%BB%87n_v%C3%A0_cao_%C4%91%E1%BA%B3ng_t%E1%BA%A1i_H%C3%A0_N%E1%BB%99i"

p <- my_link %>% 
  read_html() %>% 
  html_table(fill = TRUE) %>% 
  .[[1]]

names(p) <- c("stt", "name", "type1", "year", "n_student", "reg", "type2")

# Viết hàm lấy ra long - lat: 

library(ggmap)

get_spatial_data <- function(x) {
  result <- geocode(x, output = "latlona", source = "google")
  return(result %>% mutate(origin_add = x))
}


# DF về tọa độ của các đại học: 

u <- lapply(p$name, get_spatial_data)
u <- do.call("bind_rows", u)

# Vì chưa phải là địa chỉ chính xác nên sẽ có một số case bị NA: 

u <- na.omit(u)

# Cái bản đồ cùng vị trí của những đại học này: 
map <- get_map(location = "Hanoi", zoom = 12)

ggmap(map) + 
  geom_point(data = u, 
             aes(x = lon, y = lat), color = "red", size = 4, alpha = 0.5) + 
  theme(axis.title.x = element_text(colour = "white"),
        axis.title.y = element_text(colour = "white"),
        axis.text.x = element_text(colour = "white"),
        axis.text.y = element_text(colour = "white")) + 
  labs(title = "Some Universities Located in Hanoi")
```

